/**
 * ErrorCode definition
 *
 * Auth error:      1xx
 * Topic error:     2xx
 * Room error:      3xx
 *
 * Request error:   4xx
 * Server error:    5xx
 *
 * @export
 * @enum {number}
 */
export enum ErrorCode {
    NO_ERROR = 0,

    // VERIFY ERROR
    VERIFY_FAILED = 1,

    // AUTH ERROR
    AUTH_ACCOUNT_EXISTS = 100,
    AUTH_ACCOUNT_NOT_FOUND = 101,
    AUTH_ACCOUNT_NOT_ACTIVE = 102,
    AUTH_ACCOUNT_BLOCKED = 103,

    AUTH_REQUEST_NOT_FOUND = 110,
    AUTH_REQUEST_OTP_INVALID = 111,
    AUTH_REQUEST_IDENTITY_INVALID = 112,
    AUTH_REQUEST_PASSWORD_INVALID = 113,
    AUTH_REQUEST_METHOD_NOT_SUPPORTED = 114,
    AUTH_REQUEST_TOO_MANY = 115,

    // AUTH SIGN IN
    AUTH_SIGN_IN_USER_BUSY = 120,

    // TOPIC ERROR
    TOPIC_NOT_RUNNING = 200,
    TOPIC_NOT_FOUND = 201,
    TOPIC_SCHEDULE_NOT_FOUND = 202,
    SCHEDULE_REMINDER_REQUEST_TOO_MANY = 203,
    TOPIC_TEST_WAS_LOCKED = 204,
    TOPIC_TEST_NOT_RUNNING = 205,
    SCHEDULE_REGISTRATION_REQUEST_TOO_MANY = 206,
    SCHEDULE_REGISTRATION_SAME_TIME_SHIFT = 207,
    SCHEDULE_REGISTRATION_TIMEOUT = 208,
    CANCEL_SCHEDULE_REGISTRATION_TIMEOUT = 209,
    CANCEL_NOT_EXIST_SCHEDULE_REGISTRATION = 210,
    SCHEDULE_REGISTRATION_CONFLICT_TIME = 211,
    SCHEDULE_REGISTRATION_DIFFERENCE_LEVEL = 212,
    TOPIC_RUNNING_TIMEOUT = 213,
    TOPIC_NOT_RUNNING_AT_USER_COUNTRY = 214,
    START_TIME_FOR_REGISTER_REQUIRED = 215,
    INVALID_SCHEDULE_TIME = 216,
    EXPIRED_TIME_TO_UPDATE_SCHEDULE_REGISTRATION = 217,
    TOPIC_NOT_SUITABLE_FOR_MODERATOR = 218,
    TOPIC_SCHEDULE_IS_PROCESSING = 219,
    CAN_NOT_POP_MOD = 220,

    // ROOM ERROR
    ROOM_JOINING_BANNED = 300,
    ROOM_NOT_FOUND = 301,
    ROOM_REQUEST_EXPIRED = 302,
    ROOM_ALREADY_JOINED = 303,
    ROOM_NOT_AVAILABLE = 304,
    ROOM_USER_BUSY = 305,
    ROOM_REQUEST_TOO_MANY = 306,
    ROOM_RESUME_NOT_FOUND = 307,
    ROOM_RESUME_FOUND = 308,
    USER_NOT_IN_ROOM = 309,
    MODERATOR_NOT_IN_ROOM = 310,
    CURRENT_CALLING_NOT_FOUND = 311,
    ROOM_JOINING_BLOCKED = 312,
    ROOM_USER_JOINING_OVER_TIME = 313,
    ROOM_REQUEST_INVALID_TYPE = 314,
    ROOM_SPAM_WARNING = 315,
    ROOM_SPAM_BLOCKED = 316,
    ROOM_USER_LOCKED = 317,
    ROOM_USER_IN_CURRENT_CALLING = 318,
    ROOM_GUIDE_SELECTION_ID_NOT_CORRECT = 319,
    ROOM_BOOKING_ONLY = 320,
    ROOM_CAN_NOT_CHANGE_TOPIC = 321,

    // REQUEST ERROR
    REQUEST_VALIDATION_ERROR = 400,
    REQUEST_UNAUTHORIZED = 401,
    REQUEST_FORBIDDEN = 403,
    REQUEST_NOT_FOUND = 404,

    // SERVER ERROR
    SERVER_ERROR = 500,
    SERVER_AUTH_ERROR = 501, // and not know why
}
